django/conf/project_template/urls.py
from django.conf.urls.defaults import *

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Example:
    # (r'^{{ project_name }}/', include('{{ project_name }}.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # (r'^admin/', include(admin.site.urls)),
)

portal/groups/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('portal.groups.views',
    (r'^$', 'index'),
)

portal/polls/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('portal.polls.views',
    (r'^$', 'index'),
    (r'^poll_save/$', 'poll_save'),
    (r'^poll_edit/(?P<id>.+)/$', 'poll_save'),
    (r'^poll_detail/(?P<id>.+)/$', 'poll_detail'),
    (r'^group_save/$', 'group_save'),
    (r'^group_edit/(?P<id>.+)/$', 'group_save'),
    (r'^question_save/$', 'question_save'),
    (r'^question_edit/(?P<id>.+)/$', 'question_save'),
    (r'^choice_save/$', 'choice_save'),
    (r'^choice_edit/(?P<id>.+)/$', 'choice_save'),
    (r'^answer/(?P<id>.+)/$', 'answer'),
    (r'^send_mail/(?P<id>.+)/$', 'send_mail'),
    (r'^report/(?P<id>.+)/$', 'report'),
)

urls.py
from django.conf.urls.defaults import *
from django.contrib import admin

handler500 = 'djangotoolbox.errorviews.server_error'

from django.contrib import admin
from django.contrib.auth.views import login, logout
import os

admin.autodiscover()

urlpatterns = patterns('',
    (r'^admin/', include(admin.site.urls)),
#    (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': os.path.join(os.path.dirname(__file__), 'static')}),
    (r'^accounts/login/$', login),
    (r'^accounts/logout/$', logout, {'next_page': "/", }),
    (r'^accounts/', include('portal.accounts.urls')),
    (r'^comments/', include('django.contrib.comments.urls')),
    (r'^', include('portal.urls')),
)

portal/groups/models.py
# -*- coding: utf-8 -*-
__author__ = 'brunocatao'

from django.db import models
from django.utils.translation import ugettext as _

from portal.models import Indexable, Picture, UserInfo
from portal.fields import AutoSlugField

'''
Groups are a place where users who share similar interests can share messages,
files, pictures and so on.
There are two roles for the relationship between users and groups:
1. Owners - They administrate the group. Owners can invite other users to
            participate of the group;
2. Users  - They can post messages, files and pictures. They can join a group
            in two ways: i) accessing the group and applying for membership, or
            ii) receiving an email from an invitement from a group's owner. 
'''
class Group(Indexable):
    name        = models.CharField(_('Name'), blank=False, max_length=100)
    slug        = AutoSlugField(prepopulate_from=('acronym',), parent_name='course', unique=True, blank=True, max_length=100)
    acronym     = models.CharField(_('Acronym'), blank=True, null=True, max_length=100)
    picture     = models.ForeignKey(Picture, blank=True, null=True)
    description = models.TextField(_('Description'))
    feed_url    = models.CharField(_('News Feed URL'), blank=True, null=True, max_length=512)
    twitter_id  = models.CharField(_('Twitter ID'), blank=True, null=True, max_length=100)

class ManagerUserGroupRole(models.Manager):
    def owner_role(self):
        queryset = self.filter(slug='owner')
        if queryset.exists():
            return queryset.all()[0]
        role = UserGroupRole(name='Owner', slug='owner')
        role.save()
        return role

    def user_role(self):
        queryset = self.filter(slug='user')
        if queryset.exists():
            return queryset.all()[0]
        role = UserGroupRole(name='User', slug='user')
        role.save()
        return role

class UserGroupRole(models.Model):
    name = models.CharField(_('Role Name'), blank=False, max_length=100)
    slug = AutoSlugField(prepopulate_from=('name',), unique=True, blank=True, max_length=100)

    objects = ManagerUserGroupRole()

    class Meta:
        verbose_name        = _('Role for Group Relationship')
        verbose_name_plural = _('Roles for Group Relationship')

    def __unicode__(self):
        return self.name

class RelUserGroup(models.Model):
    user  = models.ForeignKey(UserInfo, blank=False)
    group = models.ForeignKey(Group, blank=False)
    role  = models.ForeignKey(UserGroupRole, blank=False)

portal/polls/models.py
# -*- coding: utf-8 -*-
__author__ = 'brunocatao'

import datetime

from django import forms
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import ugettext as _

QUESTION_KIND_CHOICES = (
    ('',  u'Selecione um tipo'),
    ('M', u'Múltipla Escolha'),
    ('L', u'Lickert'),
    ('D', u'Discursiva'),
)

class Poll(models.Model):
    """
    A poll, defined by a title and a set of questions.
    """
    title          = models.CharField(_('Title'), blank=False, max_length=100)
    date_published = models.DateTimeField(default=datetime.datetime.now)

    def __unicode__(self):
        return self.title

class Group(models.Model):
    """
    This class models groups of questions.
    """
    title    = models.CharField(_('Title'), blank=False, max_length=100)
    sequence = models.IntegerField(_('Sequence'), blank=True, default=0)
    poll     = models.ForeignKey(Poll)
    help     = models.CharField(_('Help'), blank=True, max_length=1024)

    def __unicode__(self):
        return '%d. %s' % (self.sequence, self.title, )

    class Meta:
        ordering = ('sequence', )

def fill_group_sequence(sender, instance, **kw):
    """This function will automatically fill the group's sequence value"""
    if instance.sequence == 0:
        instance.sequence = Group.objects.filter(poll=instance.poll).count() + 1

models.signals.pre_save.connect(fill_group_sequence, sender=Group)

class Question(models.Model):
    """
    A poll's question.
    """
    title    = models.CharField(_('Title'), blank=False, max_length=100)
    help     = models.CharField(_('Help'), blank=True, max_length=1024)
    group    = models.ForeignKey(Group)
    kind     = models.CharField(_('Kind'), blank=False, max_length=1, choices=QUESTION_KIND_CHOICES)
    sequence = models.IntegerField(_('Sequence'), blank=True, default=0)

    def __unicode__(self):
        return self.title
    
    class Meta:
        ordering = ('sequence', )

def fill_question_sequence(sender, instance, **kw):
    """This function will automatically fill the question's sequence value"""
    if instance.sequence == 0:
        instance.sequence = Question.objects.filter(group=instance.group).count() + 1

models.signals.pre_save.connect(fill_question_sequence, sender=Question)


class Choice(models.Model):
    '''
    If a question's kind is "multiple choice" than it should have choices associated.
    '''
    choice   = models.CharField(_('Choice'), blank=False, max_length=100)
    question = models.ForeignKey(Question, null=False)

    class Meta:
        ordering = ('choice', )

class Answer(models.Model):
    """
    An answer associated to a question and to a user.
    """
    answer   = models.CharField(_('Answer'), blank=False, max_length=100)
    question = models.ForeignKey(Question)

portal/groups/forms.py
__author__ = 'brunocatao'

from django import forms
from django.utils.translation import ugettext as _

from .models import Group

class GroupForm(forms.ModelForm):
    name         = forms.CharField(label=_('Name'),          required=True, max_length=100)
    acronym      = forms.CharField(label=_('Acronym'),       required=False, max_length=100)
    description  = forms.CharField(label=_('Description'),   widget=forms.Textarea)
    feed_url     = forms.CharField(label=_('News Feed URL'), required=False, max_length=512)
    twitter_id   = forms.CharField(label=_('Twitter ID'),    required=False, max_length=100)

    class Meta:
        model = Group
        fields = ('name', 'acronym', 'description', 'feed_url', 'twitter_id', )

portal/polls/forms.py
__author__ = 'brunocatao'

from django import forms
from django.utils.translation import ugettext as _

from .models import Poll, Question, Choice, Answer, Group

class PollForm(forms.ModelForm):
    class Meta:
        model = Poll

class QuestionForm(forms.ModelForm):
    help = forms.CharField(label=_('Help'), widget=forms.Textarea, required=False, max_length=1024)
    
    class Meta:
        model = Question

class ChoiceForm(forms.ModelForm):
    class Meta:
        model = Choice

class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer

class GroupForm(forms.ModelForm):
    help = forms.CharField(label=_('Help'), widget=forms.Textarea, required=False, max_length=1024)
    
    class Meta:
        model = Group

portal/groups/views.py
# -*- coding: utf-8 -*-
from django.http import HttpResponse, Http404
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.shortcuts import get_object_or_404
from django.views.decorators.csrf import csrf_protect
from django.contrib.auth.decorators import login_required
from django.views.generic.simple import direct_to_template

import re
from time import mktime
from datetime import datetime
from feedparser import feedparser

from .forms import GroupForm
from .models import Group


def index(request):
    return HttpResponse('Funciona !')

portal/polls/views.py
# -*- coding: utf-8 -*-
import csv
import traceback
import logging

from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.shortcuts import get_object_or_404
from django.views.decorators.csrf import csrf_protect
from django.contrib.auth.decorators import login_required
from django.views.generic.simple import direct_to_template
from django.forms.formsets import formset_factory

from .models import Poll, Question, Answer, Choice, Group
from .forms import PollForm, QuestionForm, ChoiceForm, AnswerForm, GroupForm

from django.template import Context
from django.template.loader import get_template
from django.core.mail import EmailMultiAlternatives

from portal.models import UserInfo, UserInstitutionRole, RelUserInstitution

def index(request):
    return HttpResponse('Funciona !')

@csrf_protect
@login_required
def poll_save(request, id=None):
    '''This function is used to create and edit polls.'''
    form = None
    ctx  = dict()

    if request.method == 'GET':
        if id:
            poll = get_object_or_404(Poll, pk=id)
            form = PollForm(instance=poll)
        else:
            form = PollForm()
    else:
        if id:
            poll = get_object_or_404(Poll, pk=id)
            form = PollForm(request.POST, instance=poll)
        else:
            form = PollForm(request.POST)

        if form.is_valid():
            poll = form.save(commit=True)

            return HttpResponseRedirect(reverse('portal.polls.views.poll_detail', args=[poll.pk,]))

    ctx['form'] = form

    return direct_to_template(request, 'polls/poll_form.html', ctx)

def poll_detail(request, id=None):
    '''This function is used to show the details of a poll.'''
    return HttpResponse("Funcionou !")

@csrf_protect
@login_required
def question_save(request, id=None):
    '''This function is used to create and edit questions associated to a poll.'''
    form = None
    ctx  = dict()

    if request.method == 'GET':
        if id:
            question = get_object_or_404(Question, pk=id)
            form     = QuestionForm(instance=question)
        else:
            form = QuestionForm()
    else:
        if id:
            question = get_object_or_404(Poll, pk=id)
            form     = QuestionForm(request.POST, instance=question)
        else:
            form = QuestionForm(request.POST)

        if form.is_valid():
            question = form.save(commit=True)

            return HttpResponseRedirect(reverse('portal.polls.views.question_save'))

    ctx['form'] = form

    return direct_to_template(request, 'polls/question_form.html', ctx)

@csrf_protect
@login_required
def choice_save(request, id=None):
    '''This function is used to create and edit questions' choices associated to a poll.'''
    form = None
    ctx  = dict()

    if request.method == 'GET':
        if id:
            choice = get_object_or_404(Choice, pk=id)
            form     = ChoiceForm(instance=choice)
        else:
            form = ChoiceForm()
    else:
        if id:
            choice = get_object_or_404(Choice, pk=id)
            form   = ChoiceForm(request.POST, instance=choice)
        else:
            form = ChoiceForm(request.POST)

        if form.is_valid():
            choice = form.save(commit=True)

            return HttpResponseRedirect(reverse('portal.polls.views.choice_save'))

    ctx['form'] = form

    return direct_to_template(request, 'polls/choice_form.html', ctx)

@csrf_protect
@login_required
def group_save(request, id=None):
    '''This function is used to create and edit groups of questions associated to a poll.'''
    form = None
    ctx  = dict()

    if request.method == 'GET':
        if id:
            group = get_object_or_404(Group, pk=id)
            form  = GroupForm(instance=group)
        else:
            form = GroupForm()
    else:
        if id:
            group  = get_object_or_404(Group, pk=id)
            form   = GroupForm(request.POST, instance=group)
        else:
            form = GroupForm(request.POST)

        if form.is_valid():
            group = form.save(commit=True)

            return HttpResponseRedirect(reverse('portal.polls.views.group_save'))

    ctx['form'] = form

    return direct_to_template(request, 'polls/group_form.html', ctx)


def answer(request, id):
    '''This function is called by users in order to answer a poll.'''
    if request.method == 'GET':
        poll = get_object_or_404(Poll, pk=id)

        question_count = 0
        for group in poll.group_set.all():
            question_count += group.question_set.count()

        class Counter:
            def __init__(self):
                self.value = -1

            def next(self):
                self.value += 1
                return self.value

            def value(self):
                return self.value

        ctx = dict()
        ctx['poll']           = poll
        ctx['question_count'] = question_count
        ctx['counter']        = Counter()


        return direct_to_template(request, 'polls/answer.html', ctx)
    else:
        AnswerFormSet = formset_factory(AnswerForm)
        formset = AnswerFormSet(request.POST, request.FILES)
        
        if formset.is_valid():
            for form in formset.forms:
                Answer(answer=form.cleaned_data['answer'],
                       question=form.cleaned_data['question']).save()

        return direct_to_template(request, 'polls/finish.html')

def send_mail(request, id):
    poll         = get_object_or_404(Poll, pk=id)
    student_role = UserInstitutionRole.objects.student_role()
    counter      = 0

    ctx = {
        'link': 'http://www.portalsaladeaula.com/polls/answer/%s' % str(poll.id),
    }

    subject      = "Por favor, responda a nossa pesquisa"
    from_email   = 'Portal Sala de Aula <gerencia@portalsaladeaula.com>'
    text_content = get_template('polls/email.txt').render(Context(ctx))
    html_content = get_template('polls/email.html').render(Context(ctx))

    for rel in RelUserInstitution.objects.filter(role=student_role).all():
        try :
            msg = EmailMultiAlternatives(subject, text_content, from_email, [rel.user.email, ])
            msg.attach_alternative(html_content, "text/html")

            try:
                msg.send()
                counter += 1
            except:
                logging.error('Não foi possível enviar o email')
                traceback.print_exc()
        except:
            pass

    return HttpResponse("%d emails enviados com sucesso" % counter)

def report(request, id):
    poll      = get_object_or_404(Poll, pk=id)
    maps      = dict()
    questions = []
    nrows     = 0

    # Create the HttpResponse object with the appropriate CSV header.
    response = HttpResponse(mimetype='text/csv')
    response['Content-Disposition'] = 'attachment; filename=poll_report.csv'
    
    writer = csv.writer(response)

    for group in poll.group_set.all():
        for question in group.question_set.all():
            questions.append(question)
            maps[question.id] = question.answer_set.all()
            nrows = len(maps[question.id])

    writer.writerow(['%d.%d' % (q.group.sequence, q.sequence, ) for q in questions])

    for i in range(nrows):
        row = []
        for q in questions:
            if q.kind == 'M': #Multiple choice
                row.append(Choice.objects.get(pk=int(maps[q.id][i].answer)).choice.encode('ascii', 'ignore'))
            else:
                row.append(maps[q.id][i].answer)
        writer.writerow(row)

    return response

templates/polls/already_answered.html
{% extends "base.html" %}
{% block content %}
    <h2>Desculpe-nos</h2>
    <br/>
    <p>
        Desculpe-nos, porém consta em nosso sistema que você já respondeu a esta pesquisa e portanto não poderá
        respondê-la novamente.
    </p>
{% endblock %}

templates/polls/answer.html
{% extends "base.html" %}
{% load media %}

{% block css %}
    {% include_media 'poll_answer.css' %}
{% endblock %}

{% block preload_js %}
    {% include_media 'poll_answer.js' %}
{% endblock %}

{% block jquery %}
    {{ block.super }}
    $(".help_img").cluetip();

    $("#my_form_id").submit(function() {
        var result = true;

        $(':radio').each(function() {
            var selected = false;

            $("input[name='" + $(this).attr("name") + "']").each(function() {
                if ($(this).is(':checked')) {
                    selected = true;
                }
            });

            if (!selected) {
                result = false;
            }
        });

        if (!result) {
            alert('Você deve responder a todas as perguntas !');
        }

        return result;
    });
    
    $("#my_form_id").validationEngine();
{% endblock %}

{% block content %}
    <h2>{{ poll.title }}</h2>
    <form action="" method="POST" id="my_form_id">
        <input type="hidden" name="form-TOTAL_FORMS"   value="{{ question_count }}" id="id_form-TOTAL_FORMS" />
        <input type="hidden" name="form-INITIAL_FORMS" value="0" id="id_form-INITIAL_FORMS" />
        <input type="hidden" name="form-MAX_NUM_FORMS" id="id_form-MAX_NUM_FORMS" />
        {% csrf_token %}
        {% for group in poll.group_set.all %}
            <h2>
                {% if group.help %}
                    <img src="{% media_url 'images/help.png' %}" title="{{ group.help }}"/>
                {% endif %}
                {{ group.sequence }}. {{ group.title }}
            </h2>
            <table>
                <thead>
                    <tr>
                        <th style="width: 40px">Ajuda</th>
                        <th style="width: 410px">Questão</th>
                        <th style="width: 50px">Não concordo totalmente</th>
                        <th style="width: 50px">Não concordo parcialmente</th>
                        <th style="width: 50px">Indeciso</th>
                        <th style="width: 50px">Concordo parcialmente</th>
                        <th style="width: 50px">Concordo totalmente</th>
                    </tr>
                </thead>
                {% for question in group.question_set.all %}
                <tr class="poll_question">
                    <td style="text-align: center">
                        {% comment %}The fields below are for the ManagementForm data{% endcomment %}
                        <input type="hidden" name="form-{{ counter.next }}-question" id="id_form-{{ counter.value }}-question" value="{{ question.id }}"/>

                        {% if question.help %}
                            <img class="help_img" src="{% media_url 'images/help.png' %}" title="{{ question.help }}"/>
                        {% else %}
                            &nbsp;
                        {% endif %}
                    </td>
                    <td>
                        {% comment %}Question's title{% endcomment %}
                        <label for="id_form-{{ counter.value }}-answer">
                            {{ group.sequence }}.{{ question.sequence }}. {{ question.title }}
                        </label>
                    </td>
                    {% comment %}Below we render the field for answer the question according to its kind{% endcomment %}
                    {% if question.kind == 'M' %} {% comment %} Multiple Choices {% endcomment %}
                        <td colspan="5">
                            <select name="form-{{ counter.value }}-answer" id="id_form-{{ counter.value }}-answer" class="validate[required]">
                                <option value="" selected="selected">---------</option>
                                {% for choice in question.choice_set.all %}
                                <option value="{{ choice.id }}">{{ choice.choice }}</option>
                                {% endfor %}
                            </select>
                        </td>
                    {% endif %}
                    {% if question.kind == 'L' %} {% comment %} Lickert Scale {% endcomment %}
                        <td><input type="radio" name="form-{{ counter.value }}-answer" class="validate[required]" value="1"/></td>
                        <td><input type="radio" name="form-{{ counter.value }}-answer" class="validate[required]" value="2"/></td>
                        <td><input type="radio" name="form-{{ counter.value }}-answer" class="validate[required]" value="3"/></td>
                        <td><input type="radio" name="form-{{ counter.value }}-answer" class="validate[required]" value="4"/></td>
                        <td><input type="radio" name="form-{{ counter.value }}-answer" class="validate[required]" value="5"/></td>
                    {% endif %}
                    {% if question.kind == 'D' %} {% comment %} Discursive {% endcomment %}
                        <td colspan="5">
                            <input name="form-{{ counter.value }}-answer" id="id_form-{{ counter.value }}-answer" type="text" class="validate[required]"/>
                        </td>
                    {% endif %}
                </tr>
                {% endfor %}
            </table>
        {% endfor %}
        <p>
           <input type="submit" value="Enviar Respostas"/>
        </p>
    </form>
{% endblock %}

templates/polls/choice_form.html
{% extends "form.html" %}
{% load i18n %}

{% block form_title %}<h2>{% trans "Choice's Data" %}</h2>{% endblock %}

templates/polls/email.html
<p>Caro aluno!</p>
<br/>
<p>Por favor acesse o link abaixo e preencha a pesquisa: <a href="{{ link }}">Clique Aqui !</a></p>

<p>Essa pesquisa tem como objetivo avaliar a qualidade do Portal Sala de Aula na perspectiva do usuário pertencente à categoria aluno. Atualmente, fazem parte dessa categoria de usuários alunos dos cursos de Sistemas de Informação e de Direito da FACISA.</p>
<p>Essa pesquisa está associada a um projeto de pesquisa experimental dentro do programa de doutorado da Profa. Vera Medeiros, vice-coordenadora do Curso de Sistemas de Informação, que prevê o uso de métodos estatísticos avançados na análise dos dados relativos à percepção de qualidade do Portal Sala de Aula, um artefato associado à pesquisa de mestrado (em andamento) do Prof. Bruno Catão. Do ponto de vista prático, o resultado dessa pesquisa propiciará a revelação de aspectos referentes ao portal que requerem melhorias e aprimoramentos.</p>
<p>Estão aptos a participar da pesquisa todos os alunos dos cursos de Sistemas de Informação e de Direito  que cursaram, no período de 2011-1, uma ou mais disciplinas as quais utilizaram pouco ou intensivamente os serviços do Portal Sala de Aula.</p>
<p>O instrumento de pesquisa é um questionário, cujas questões, com exceção daquelas relacionadas às informações demográficas, deverão ser respondidas usando-se uma Escala Likert de 5 pontos (1 – Discordo Totalmente,  5 – Concordo Totalmente). De acordo com a metodologia científica, apenas questionários totalmente respondidos (com todas as suas questões demográficas e referentes ao modelo de avaliação da efetividade do portal respondidas) poderão ser considerados aptos a participarem do processo de análise estatística dos dados. Portanto, uma ou mais questões em um questionário sem resposta, invalida o mesmo.</p>
<p>Por gentileza, dedique alguns minutos do seu tempo para responder a esta pesquisa e ajude-nos a ampliar o papel do Portal Sala de Aula na geração de valor no processo de desenvolvimento de suas atividades acadêmicas.</p>
<br/>
<br/>
<p>Atenciosamente,</p>
<p>Profa. Vera Medeiros e Prof. Bruno Catão</p>

templates/polls/finish.html
{% extends "base.html" %}
{% block content %}
    <h2>Muito Obrigado</h2>
    <br/>
    <p>Nós que fazemos o <b>Portal Sala de Aula</b> agradecemos bastante a sua participação.</p>
{% endblock %}

templates/polls/group_form.html
{% extends "form.html" %}
{% load i18n %}

{% block form_title %}<h2>{% trans "Groups's Data" %}</h2>{% endblock %}

templates/polls/poll_form.html
{% extends "form.html" %}
{% load i18n %}

{% block form_title %}<h2>{% trans "Poll's Data" %}</h2>{% endblock %}

templates/polls/question_form.html
{% extends "form.html" %}
{% load i18n %}

{% block form_title %}<h2>{% trans "Question's Data" %}</h2>{% endblock %}